export const TRANSACTION_TYPES = {
  TRANSFER: 'TRANSFER',
  DEPOSIT: 'DEPOSIT',
  WITHDRAWAL: 'WITHDRAWAL',
};
export const TRANSACTION_TYPE_VALUES = Object.values(TRANSACTION_TYPES);

export const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  FLAGGED: 'FLAGGED',
  REVERSED: 'REVERSED',
};
export const TRANSACTION_STATUS_VALUES = Object.values(TRANSACTION_STATUS);